//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KProyecto.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDetalle
    {
        public long IdDetalle { get; set; }
        public long IdMaestro { get; set; }
        public long IdProducto { get; set; }
        public decimal Precio { get; set; }
        public int Cantidad { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Impuesto { get; set; }
        public decimal Total { get; set; }
    
        public virtual TMaestro TMaestro { get; set; }
        public virtual TProducto TProducto { get; set; }
    }
}
