//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KProyecto.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMaestro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TMaestro()
        {
            this.TDetalle = new HashSet<TDetalle>();
        }
    
        public long IdMaestro { get; set; }
        public long IdUsuario { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public decimal TotalPagado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDetalle> TDetalle { get; set; }
        public virtual TUsuario TUsuario { get; set; }
    }
}
